#!/usr/bin/env sh

set_global_settings() {
    yabai -m config window_origin_display default
    yabai -m config window_placement second_child
    yabai -m config window_topmost on
    yabai -m config window_shadow float
    yabai -m config window_opacity on
    yabai -m config window_opacity_duration 0.0
    yabai -m config active_window_opacity 1.0
    yabai -m config normal_window_opacity 1.0
    yabai -m config window_border on
    yabai -m config window_border_width 4
    yabai -m config active_window_border_color 0xffd3d3d3
    yabai -m config normal_window_border_color 0xffc0c0c0
    yabai -m config insert_feedback_color 0xffdcdcdc
    yabai -m config split_ratio 0.50
    yabai -m config auto_balance off

    yabai -m config focus_follows_mouse on
}

set_space_settings() {
    yabai -m config layout bsp
    yabai -m config top_padding 00
    yabai -m config bottom_padding 00
    yabai -m config left_padding 00
    yabai -m config right_padding 00
    yabai -m config window_gap 06
}

set_unmanaged_apps() {
    local apps="^(System Settings|Finder|Calculator|Disk Utility|System Information|Activity Monitor|Notes|Calendar|Keychain Access|TextEdit|Stats|Alfred|LinearMouse|Dropover|OnyX|BetterTouchTool|Moonlight|AnyDesk|UTM|LuLu|Netiquette)$"
    yabai -m rule --add app="${apps}" manage=off
}

set_browser_rules() {
    local browsers="^(Safari|Firefox Developer Edition|Firefox|Tor Browser)$"
    yabai -m rule --add app="${browsers}" manage=on space=2
    yabai -m config --space 2 layout stack
}

set_signals() {
    local browsers="^(Safari|Firefox Developer Edition|Firefox|Tor Browser)$"
    yabai -m signal --add event=window_created app="${browsers}" action="yabai -m window \$YABAI_WINDOW_ID --focus"
    yabai -m signal --add event=window_focused app="${browsers}" action="yabai -m window --toggle zoom-fullscreen"
}

main() {
    set_global_settings
    set_space_settings
    set_unmanaged_apps
    set_browser_rules
    set_signals
}

main

echo "Yabai Configuration Loaded..."
