#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#sudo yabai --load-sa

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse on \
	window_origin_display default \
	window_placement second_child \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 00 \
	bottom_padding 00 \
	left_padding 00 \
	right_padding 00 \
	window_gap 12 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \

yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add title="Preferences" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add title="Software Update" manage=off
yabai -m rule --add app="Notes" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Keychain Access" manage=off
yabai -m rule --add app="TextEdit" manage=off

yabai -m rule --add app="Stats" sticky=on manage=off
# yabai -m rule --add app="Google Chrome" manage=off
yabai -m rule --add app="^Alfred$" sticky=on manage=off
yabai -m rule --add app="^LinearMouse$" manage=off
yabai -m rule --add app="CrossOver" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Dropover$" manage=off
yabai -m rule --add app="^OnyX$" manage=off
yabai -m rule --add app="^BetterTouchTool$" manage=off
yabai -m rule --add app="Moonlight" manage=off
yabai -m rule --add app="AnyDesk" manage=off
yabai -m rule --add app="Cisco Packet Tracer" title!="Cisco Packet Tracer" manage=off
yabai -m rule --add app="ZeroTier" manage=off

yabai -m rule --add title="Empty Vulkan Window" manage=off
# yabai -m rule --add title="FrmMain" manage=off
# yabai -m rule --add title="main" manage=off

borders active_color=0xff7aa2f7 inactive_color=0x80565f89 width=5.0 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
